### ISSUE TITLE
Capital : Capital Input

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#1]

**Comment by rlautt** [comment]
![image](https://user-images.githubusercontent.com/6751792/79522322-38dc1180-8010-11ea-8edc-a4ae95c3ca6c.png)

**Comment by rlautt** [comment]
INSERT seems to be off for Cap Input:
![image](https://user-images.githubusercontent.com/6751792/81596658-4ec3c480-9379-11ea-8643-dd5e661de7db.png)

**Comment by afs1jes** [comment]
Inserting works now... so does Actuals Formatting on fixed dataset Summary... fixed formatting works like current Prod for other fixed datasets.

**Comment by stuartratner** [comment]
Passed all checks

**Comment by kclark-a3** [comment]
In weekly status meeting today, CHN stated that this template is no longer being used by them.
