### ISSUE TITLE
Compensation : Input FTE Count

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#14]

**Comment by csoroka** [comment]
Actual scenarios not available to choose to test this model.

**Comment by afs1jes** [comment]
I've updated the template to allow selection of any scenario.

**Comment by csoroka** [comment]
Christina Soroka has created a secure e-mail message for you at:

https://ssl.datamotion.com/r.aspx?b=16&eh=ZVLYiXmcwE_AWVTlG7-hUA&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.


If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.


Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Compensation : Input FTE Count (#14) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Created: 5/19/2020  2:25:17 PM (UTC-04:00:00) 
Message Expires: 8/19/2020  2:25:17 PM (UTC-04:00:00)

Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by afs1jes** [comment]
(details copied from secure e-mail)

Tracking: | #48356851
-- | --
Sent: | 5/19/2020 2:25:17 PM (UTC-04:00:00)
Expires: | 8/19/2020 2:25:17 PM (UTC-04:00:00)
From: | csoroka@chnct.org
Subject: | RE: [afs1jes/CHNCT-Migration] Compensation : Input FTE Count (#14)
To: | reply+APBBA2OLTJJ5GZD7EKUW4XF4Z7MVTEVBNHHCA4FH6Y@reply.github.com, CHNCT-Migration@noreply.github.com
CC: | comment@noreply.github.com, dblaney@chnct.org
 
Tested this template with entering the 12/19 actuals.Worked perfectly.Can be changed to “client accepted”

**Comment by csoroka** [comment]
Hello - 
The Full Year column is not calculating the average correctly.  It should be the average of the populated months.

**Comment by afs1jes** [comment]
Both datasets were inappropriately set to change #missing to zeros. That caused the averages to calculate inaccurately. I've updated the datasets and it appears to be working now.

**Comment by csoroka** [comment]
Thank you for correcting - It looks good

**Comment by csoroka** [comment]
I ran this report for 2022 actuals, I was surprised not to see any data since production was copied over yesterday.  The shading of this report should not be impacted by the actual flags.  (please go into current prod to see formatting)

Thank you,
chrissy

**Comment by AVHuntley** [comment]
Ah ha! Yes, there was apparently an issue with the data refresh process where that one account, [Staffing FTE], didn't get updated correctly. I believe I have fixed that issue and reloaded the data correctly. Now I'm seeing numbers show up on this report.

I also adjusted the formatting so that it's not affected by Actuals flags.

**Comment by csoroka** [comment]
Looks good!
