### ISSUE TITLE
Finance : Variance by Cost Center

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#25]

**Comment by csoroka** [comment]
Format need to be "fit to one page" for printing.
Also can you fix the border formatting under YTD (should be the same as monthly) there are double lines under the second column and variance column where there shouldn't be.
Thank you,
Chrissy

**Comment by afs1jes** [comment]
Set to fit 1 page wide by 99 tall.

Copied formatting from month columns to YTD columns.

**Comment by csoroka** [comment]
Formatting for totals still need to be fixed.  See attached file
[NEW Sys -  Variance by Cost Center_for_Total CHN_Net Income_2019 Original Budget_Dec.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/4609227/NEW.Sys.-.Variance.by.Cost.Center_for_Total.CHN_Net.Income_2019.Original.Budget_Dec.xlsx)

**Comment by zgrose** [comment]
Seems like F6 should say Actuals and F7:F8 should have the actual scenario name? Actuals without a year is ambiguous until you secret know to reference the year in J6:J9.

![Annotation 2020-06-09 135934](https://user-images.githubusercontent.com/5044847/84188889-ef310580-aa59-11ea-9813-79729ca87335.png)

**Comment by afs1jes** [comment]
updated columns to display year when Actuals. Applied to all 4 retrieved columns and also applied to the other Variance reports (8 in all).

**Comment by afs1jes** [comment]
_transactions template version of transaction drill formatting sheet applied.

**Comment by csoroka** [comment]
Only current issue I see is the first column for the month and the first column for YTD.  There are double lines for the formatting as the rest are single lines.  It doesn't matter which one is chosen as long as they are the same for the Total across the row.

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by csoroka** [comment]
Thank you, but it doesn't look like the boarders on the sub totals and total rows have been fixed

**Comment by csoroka** [comment]
Any update on this?

**Comment by afs1jes** [comment]
I've reset the borders on all the format rows and it looks correct to me. Please let me know if it still looks off to you.

**Comment by csoroka** [comment]
Looks good – Client Accepted

Thank you

**Comment by kclark-a3** [comment]
- Zero config itemizations
- Template transactions

**Comment by csoroka** [comment]
Ran this report to compare the 2022 Org Budget vs 2022 Actuals for March 2022 (net income):
(1) When I drill into LID I noticed the column totals do not tie to the totals on the data tab
(2) On the LID drill down can you add the LOB & CC for the row data?

Thank you,
Chrissy

**Comment by kclark-a3** [comment]
Update
(2) On the LID drill down can you add the LOB & CC for the row data? **done**

**Comment by csoroka** [comment]
I re-ran this report for non-labor only and the LID totals tie.  
When running the non labor Variance by CC, I did notice the "#VALUE" error coming over on the data tab.
Can you correct it to show zero?

-Chrissy

**Comment by kclark-a3** [comment]
update

When running the non labor Variance by CC, I did notice the "#VALUE" error coming over on the data tab.
Can you correct it to show zero? **- #VALUE" error was fixed,**

**Comment by csoroka** [comment]
Thank you for fixing the error

**Comment by csoroka** [comment]
For some reason when I run/print this report for FAL & HLD the date and time displays as "######"
When I ran CHN & FDN it displayed just fine

**Comment by kclark-a3** [comment]
Date and time now displays for CHN and FDN.
[Variance by Cost Center for_2022 Original Budget_May_Total CHN_Subtotal Non-Labor Expense.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/9133577/Variance.by.Cost.Center.for_2022.Original.Budget_May_Total.CHN_Subtotal.Non-Labor.Expense.xlsx)

[Variance by Cost Center for_2022 Original Budget_May_Total FDN_Subtotal Non-Labor Expense.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/9133579/Variance.by.Cost.Center.for_2022.Original.Budget_May_Total.FDN_Subtotal.Non-Labor.Expense.xlsx)

**Comment by csoroka** [comment]
Looks good thank you
