### ISSUE TITLE
Finance : Variance by LOB and CC

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#26]

**Comment by csoroka** [comment]
Email sent 2/26/20:
Fit printing to one page
There seem to be double lines under the YTD Actuals and Variance column for the Other LOBs subtotal row (it looks fine on the monthly columns).

Thank you,
Chrissy

**Comment by afs1jes** [comment]
Set to fit 1 page wide by 99 tall.

Set top and bottom borders on Grand format rows.

**Comment by csoroka** [comment]
Christina Soroka has created a secure e-mail message for you at:

https://ssl.datamotion.com/r.aspx?b=16&eh=4gkLMeKrS0COdeLFHvh9pA&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.


If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.


Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Finance : Variance by LOB and CC (#26) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Created: 5/8/2020  11:47:54 AM (UTC-04:00:00) 
Message Expires: 8/8/2020  11:47:54 AM (UTC-04:00:00)

Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by csoroka** [comment]
Looks good  - I see you moved it over to Client Accepted - thank you

**Comment by csoroka** [comment]
Not sure what happened but it looks like the formatting of the last total row has double lines again only in the monthly second scenario column and the variance columns.

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by csoroka** [comment]
Thank you, but it looks like the formatting of the total row borders are still an issue

**Comment by csoroka** [comment]
Any update on this?

**Comment by afs1jes** [comment]
I've reset all the borders on the format rows and it looks correct to me. Can you check and let me know if it looks good to you?

**Comment by csoroka** [comment]
Looks good – client accepted

Thank you

**Comment by kclark-a3** [comment]
- Zero config itemizations
- Template transactions

**Comment by csoroka** [comment]
Ran this report to compare the 2022 Org Budget vs 2022 Actuals for March 2022 (net income):
(1) When I drill into LID I noticed the column totals do not tie to the totals on the data tab
(2) On the LID drill down can you add the LOB & CC for the row data?

Thank you,
Chrissy

**Comment by csoroka** [comment]
I realized that running it for net income that the LID totals will not tie due to staffing expenses.  So I ran it for non-labor and they tie 
However, we need the variance formulas updated so they will not result in a "#VALUE" and instead result in 0 variance.

Thank you,
Chrissy

**Comment by kclark-a3** [comment]
update

However, we need the variance formulas updated so they will not result in a "#VALUE" and instead result in 0 variance. **- "#VALUE" error was fixed**

**Comment by csoroka** [comment]
Something happen to the formatting of the date cell "G7" only showing #####
Also column "I" has a different boarder format then the other columns

Thank you,
Chriss
[Var by LOB & CC screen print.docx](https://github.com/afs1jes/CHNCT-Migration/files/8892268/Var.by.LOB.CC.screen.print.docx)
y

**Comment by kclark-a3** [comment]
update
cell "G7" now showing date and time instead of #####
borders were removed from between default cells in column I

**Comment by csoroka** [comment]
I confirmed that these items are fixed.  Thank you
I found one more issue for the Variance % column.  I noticed that variance % cells, that are forcing a 100.0% (that were previously errors), are staying positive regardless if the variance is a negative or positive amount.

**Comment by kclark-a3** [comment]
Update

I found one more issue for the Variance % column. I noticed that variance % cells, that are forcing a 100.0% (that were previously errors), are staying positive regardless if the variance is a negative or positive amount. **- fixed**

[Variance by LOB & CC for_2021 Actuals_Dec_Net Income (1).xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8912101/Variance.by.LOB.CC.for_2021.Actuals_Dec_Net.Income.1.xlsx)

**Comment by csoroka** [comment]
Looks good

**Comment by csoroka** [comment]
I ran this report for:
2014 Revised Budget vs 2015 Revised Budget, Non Labor, CHN & CHNCT (December)
When I pulled up the LID for 01-612 Dec YTD, for both scenarios, it does not match the data tab totals

**Comment by kclark-a3** [comment]
Can you please attach the built model with the discrepancy highlighted?

**Comment by kclark-a3** [comment]
Based on how A3 works, drilling for LID on YTD will only return LID and won't include Actuals

**Comment by csoroka** [comment]
Thank you for the update - we will moved this to completed
