### ISSUE TITLE
Finance : Variance by LOB

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#27]

**Comment by csoroka** [comment]
Email sent 1/31/2020 -
Can you format the YTD columns the same as the Monthly columns and fit the printing to one page (landscape)

Thank you,
Chrissy

**Comment by afs1jes** [comment]
Set to print on page wide by 99 tall.

Set Grand frothing to Top and Bottom borders.

**Comment by csoroka** [comment]
Christina Soroka has created a secure e-mail message for you at:

https://ssl.datamotion.com/r.aspx?b=16&eh=X1oSQ6nXS0mBCkh2JvIG2Q&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.


If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.


Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Finance : Variance by LOB (#27) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Created: 5/8/2020  11:51:45 AM (UTC-04:00:00) 
Message Expires: 8/8/2020  11:51:45 AM (UTC-04:00:00)

Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by afs1jes** [comment]
I copied over the formatting from the Variance by LOB and CC... I also corrected the default filename to use the ${Time} token.

**Comment by csoroka** [comment]
Looks good thank you - can be moved over to "Client Accepted"

**Comment by csoroka** [comment]
See prior comment from 22 day ago

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by csoroka** [comment]
Noticed that the second row of GL Transaction comments has a dollar size?
Thank you for fixing  the period

**Comment by kclark-a3** [comment]
- Zero config itemizations
- Template transactions

**Comment by csoroka** [comment]
Ran this report to compare the 2022 Org Budget vs 2022 Actuals for March 2022 (net income):
(1) Can you increase the data tab column, that contains the date/time that the report was run, to 31 width?
(2) When I drill into LID I noticed the column totals do not tie to the totals on the data tab
(3) On the LID drill down can you add the LOB & CC for the row data?
(3) When I drill into GL transactions, the totals on that tab do not tie to the totals on the data tab 

Thank you,
Chrissy

**Comment by kclark-a3** [comment]
Update
(1) Can you increase the data tab column, that contains the date/time that the report was run, to 31 width? **done**
(3) On the LID drill down can you add the LOB & CC for the row data? **done**

**Comment by kclark-a3** [comment]
Update: issues below were fixed

(2) When I drill into LID I noticed the column totals do not tie to the totals on the data tab
(3) When I drill into GL transactions, the totals on that tab do not tie to the totals on the data ta

**Comment by csoroka** [comment]
Looks good - just need to test for FAL, FDN & HLD once the LID is copied over

**Comment by csoroka** [comment]
looks good
