### ISSUE TITLE
Finance : Trend by Cost Center

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#28]

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by kclark-a3** [comment]
- Zero config itemizations
- Template transactions

**Comment by kclark-a3** [comment]
- Zero config itemizations
- Template transactions

**Comment by csoroka** [comment]
Will test LID drill down once FAL, FDN & HLD is uploaded
Other than that it looks good

**Comment by csoroka** [comment]
I ran this report for the 2019 Revised budget for Non Labor for all four companies (it seems to display actuals through June however the drill down for LID only display actuals through May):
Can you expand column K to be able to see the account number (width 8.50)?

**Comment by kclark-a3** [comment]
This template now displays actuals for Jan thru Jun.

If column K is expanded to 8.5 then you'll also see partial account name; see attached file and please confirm that is what you want.

[Trend by Cost Center for_2019 Revised Budget_Total CHN_Subtotal Non-Labor Expense.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/9057801/Trend.by.Cost.Center.for_2019.Revised.Budget_Total.CHN_Subtotal.Non-Labor.Expense.xlsx)

**Comment by csoroka** [comment]
I think that it only shows part of the department name because there is nothing in the display column at this time.  I'm fine with leaving it as is with the thought that one day they may use the sort order column.

This looks good thank you for fixing the issue with June
