### ISSUE TITLE
Finance : Flag Value Input

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#32]

**Comment by csoroka** [comment]
Looks like this was corrected from my 3/2/2020 email - please mover to "Client Accepted"

**Comment by csoroka** [comment]
Would like to test this template at the same time as testing the import of monthly actual data.
Makes the most sense.

**Comment by csoroka** [comment]
Test the template since Apr & May was imported by A-3 recently to test the Load process.
It worked appropriately.

**Comment by AVHuntley** [comment]
<s>Note for us - Add the Capital Flag maintenance grid to this template, have it automatically pull and update values from other grid.</s>

Nevermind, working as intended. That is, this model doesn't really get used. For testing, just double check that values submit and retrieve correctly.
