### ISSUE TITLE
Finance : Data Load Confirmation

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#36]

**Comment by csoroka** [comment]
After our call today I test the Data Load Confirmation Template
(on the call we uploaded YTD Apr actual transactions into the new prod)
Unfortunately the excel data result from running the confirmation didn't look accurate in comparison to the current prod.
I have attached both reports.
[Data Load Confirmation Apr 2022 new prod.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8911449/Data.Load.Confirmation.Apr.2022.new.prod.xlsx)
[DataLoadTieOutDataLoadStagingApr current prod.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8911450/DataLoadTieOutDataLoadStagingApr.current.prod.xlsx)

**Comment by kclark-a3** [comment]
Please send me copies of the data files so that I can do testing.

**Comment by csoroka** [comment]
April actual data that was uploaded into the new system yesterday 6/15/2022:

[CHNCT Beginning Balances.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8919991/CHNCT.Beginning.Balances.xlsx)
[CHN Detail.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8919994/CHN.Detail.xlsx)
[FAL Detail.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8919996/FAL.Detail.xlsx)
[FDN Detail.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8919997/FDN.Detail.xlsx)
[HLD Detail.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8919999/HLD.Detail.xlsx)

**Comment by kclark-a3** [comment]
Update

After doing a data load in .NET and reconciliation between Java and .Net, the issue appears to be not in the data itself but the difference in sign for the amounts (-/+).

In the file attached, you'll see for example, that the only difference between the amounts in Java and .Net for lob 07 and accounts 3200, 3500, 3210 are the sign of the amounts  (-/+). Additionally, account 1022 is the exact same in both systems.

.Net appears to be correct as these are revenue accounts with credit values and an asset account with a debit balance. There are many similar examples like these especially for dept 000- balance sheet related CC.

**Note: the new system loads accounts according to their natural debit or credit balances.**

**Please confirm which is correct, Java or .Net is correct.**

[Java.NetRecon.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8922303/Java.NetRecon.xlsx)

**Comment by kclark-a3** [comment]
**DISREGARD PREVIOUS MESSAGE!**

The formula that changes the sign of the amounts for some accounts in the data load template in .Net was corrected and the balances in both systems now tie for the income statement.

[Data Load Confirmation May 2022.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8923592/Data.Load.Confirmation.May.2022.xlsx)

[DataLoadTieOutDataLoadStagingMay.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8923594/DataLoadTieOutDataLoadStagingMay.xlsx)

[Java.NetRecon.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8923597/Java.NetRecon.xlsx)

**Comment by csoroka** [comment]
I reviewed the "Data Load Confirmation May 2022.xlsx" file
It seems as if the asset line isn't producing the correct data - please run this same template out of current production for May Data Load Staging
Row 32 of the Data Confirmation should be zero across as a double check

Thank you,
Chrissy

**Comment by kclark-a3** [comment]
Update

Template was updated.


[Data Load Confirm May (2).xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8953119/Data.Load.Confirm.May.2.xlsx)

**Comment by csoroka** [comment]
Looks good
