### ISSUE TITLE
Finance : Input for Enrollment Membership

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#39]

**Comment by csoroka** [comment]
Ran the template for the 2019 actuals - entered in Dec and submitted.  Went back into the template and the data was saved and the total updated appropriately.

**Comment by csoroka** [comment]
I got the following error when I tried to open up this template:
The page cannot be displayed because an internal server error has occurred.

**Comment by kclark-a3** [comment]
update

model now builds with no error from the server.

**Comment by csoroka** [comment]
Looks good - thank you
