### ISSUE TITLE
Finance : Query GL Transactions

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#41]

**Comment by csoroka** [comment]
I got the following error when I tried to open up this template:
The page cannot be displayed because an internal server error has occurred.

**Comment by kclark-a3** [comment]
update

Model now builds with no error message from the server.

**Comment by csoroka** [comment]
Ran the February 2022 GL Transactions in current prod vs new prod.
The total amount of the report(s) do not match, but they seem to have the same number of rows.  Not sure of the disconnect
See attached

[GL Transactions Query for Feb_2022 Actuals new prod.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8891868/GL.Transactions.Query.for.Feb_2022.Actuals.new.prod.xlsx)
[GLTransactionsQueryforFeb_2022Actuals current prod.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8891869/GLTransactionsQueryforFeb_2022Actuals.current.prod.xlsx)

**Comment by kclark-a3** [comment]
Update
The new system loads amounts in the correct debit or credit state and the old (current production) system did not. For example, the 401k payable highlighted in the attached file, shows as a debit in the old system (java) and a credit in the new (.net). Please confirm that this is correct

[GLTrxQueryRecon.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8895055/GLTrxQueryRecon.xlsx)
.

**Comment by csoroka** [comment]
Thank you for explaining, that makes sense.
This looks good
