### ISSUE TITLE
Finance : Variance by Cost Center w/ Salary

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#47]

**Comment by csoroka** [comment]
Located in both Administration section and Financial Reporting section.  Should not be located in the "Financial Reporting" section since it shows the detailed salary info.

Thank you,
Chrissy

**Comment by afs1jes** [comment]
the template has been removed from the Finance Reporting area.... it remains in the Admin folder.

**Comment by csoroka** [comment]
Christina Soroka has created a secure e-mail message for you at:

https://ssl.datamotion.com/r.aspx?b=16&eh=JHbNqiR_s0K2ygw42yX5uw&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.


If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.


Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Finance : Variance by Cost Center w/ Salary (#47) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Created: 5/8/2020  11:42:08 AM (UTC-04:00:00) 
Message Expires: 8/8/2020  11:42:08 AM (UTC-04:00:00)

Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by csoroka** [comment]
Ran this report for 5010 for CHNCT all lines of business.  Can you please update the formatting to fit the report on one page.  Also I noticed the borders for the total row do not match for all the columns.  Should be a solid line for the top of the row.  Thank you

**Comment by afs1jes** [comment]
I reduced the scale percentage to 80%. Since the columns auto fit, it's possible that some reports may still require the user to tweak the scaling as they print. But this new setting should get more reports to print on one page without the user needing to check.

The lines looked good to me until printing.... but I see what you mean and have reset all the Grand Total Formatting to have a solid line on top. It looks better to me in print preview.

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by csoroka** [comment]
This is what the borders for the total rows look like (before printing - not in preview).  Not sure why it looks okay on your end but not on mine.
In addition, the print preview shows the report on two pages.

[Variance by Cost Center with salary.docx](https://github.com/afs1jes/CHNCT-Migration/files/5435865/Variance.by.Cost.Center.with.salary.docx)

**Comment by csoroka** [comment]
Any input on this?

**Comment by afs1jes** [comment]
I've reapplied the borders and they still look good to me... can you test again and see if they look good to you too?

Also, I've adjusted the print to scale to 75%. Hopefully that will catch any of the overflow you're seeing. Please note that your current prod system prints at 100% and, with these selections, it also spills over to 2 pages wide..... and the borders in the old are also not consistent across all columns.

**Comment by csoroka** [comment]
Christina Soroka has created a secure e-mail message for you at:
https://ssl.datamotion.com/r.aspx?b=16&eh=ABo4R6SOGE_tnLIWDdWhiA&cb=chnct1

To access your message, simply follow these steps:

1. Click on the above link. 
2. You will be prompted to create a password to protect your account.
3. Access your Inbox to view your message.

Problems accessing the message?
- If you are unable to open the link, please make sure that your firewall or your company's security settings are not blocking the link.
- If you are unsure of your password, please reset it at https://ssl.datamotion.com/ by clicking on the "Click HERE to reset your password" link.

Additional Help:
•		Questions relating to the content of the e-mail should be directed to the sender or sending organization.
•		Questions relating to reading this secure message can be sent to helpdesk@chnct.org.


--------------------------------------------------------------------------------
Message Details: 
Subject: RE: [afs1jes/CHNCT-Migration] Finance : Variance by Cost Center w/ Salary (#47) 
From: csoroka@chnct.org 
To: reply@reply.github.com 
Message ID: 50908328
Created: 11/6/2020  12:10:04 PM (UTC-05:00:00) 
Expires: 2/6/2021  12:10:04 PM (UTC-05:00:00)
--------------------------------------------------------------------------------
Copyright (c) 1996-2020 DataMotion, Inc.

**Comment by afs1jes** [comment]
from secure mail:

This looks good, thank you so much (Client accepted)

**Comment by csoroka** [comment]
Looks good
