### ISSUE TITLE
Finance : Variance by LOB and CC w/ Salary

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#48]

**Comment by csoroka** [comment]
Ran for Total CHNCT for 2019 Org Budget vs 2019 Actuals for November - the amounts are accurate.
The formatting of the subtotals (second to last line) for the second scenario and the variance need to be fixed.

**Comment by afs1jes** [comment]
Rollup formatting updated. column headers updated to display year when "actuals".

**Comment by csoroka** [comment]
Ran the Var by LOB & CC w/ salary - can you please fit this report to one page?  Also the formatting of the total borders are not consistent.

**Comment by afs1jes** [comment]
I've confirmed reset the Grand Total Formatting row so that it has the same top border on all columns and I reset the print scaling to 75%.

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by csoroka** [comment]
Formatting looks great, thank you

**Comment by csoroka** [comment]
You can move this to client accepted

**Comment by csoroka** [comment]
Looks good

**Comment by kclark-a3** [comment]
Based on how A3 works, drilling for LID on YTD will only return LID and won't include Actuals
