### ISSUE TITLE
Finance : CHNCT Budget Comparison Report by Account

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#51]

**Comment by afs1jes** [comment]
_transactions sheet modified the header so that the Period displays the queried period rather than the period of the first record returned.

**Comment by csoroka** [comment]
Hello - 
I ran this report for 2021 Actuals vs 2021 Org Budget vs 2022 Org Budget and I noticed that the Revenue is appearing twice (located under Administrative Expenses in error)

**Comment by kclark-a3** [comment]
Update

Revenue is no longer showing twice in the report.

[CHNCT Budget Comparison Report by Account for LOB Combined CHNCT (1).xlsx](https://github.com/afs1jes/CHNCT-Migration/files/8912187/CHNCT.Budget.Comparison.Report.by.Account.for.LOB.Combined.CHNCT.1.xlsx)

**Comment by csoroka** [comment]
Looks good
