### ISSUE TITLE
Capital : Capital Guidelines

### ISSUE THREAD

**Issue by afs1jes** [afs1jes/CHNCT-Migration#6]

**Comment by dblaney** [comment]
No data for years 2023 & 2024.  Years 2022 & 2025 are correct
[Capital Guideline Maintenance Test 07.12.2022.xlsx](https://github.com/afs1jes/CHNCT-Migration/files/9096111/Capital.Guideline.Maintenance.Test.07.12.2022.xlsx)

**Comment by kclark-a3** [comment]
This was fixed.

**Comment by dblaney** [comment]
This looks good.  Thank you
